# Generated by Django 6.0.5 on 2026-05-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('address_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('home', models.CharField(blank=True, max_length=50, null=True)),
                ('billing', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('picture', models.TextField()),
                ('landing_page', models.CharField(max_length=100)),
                ('logged_pages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('phone_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('work', models.CharField(blank=True, max_length=50, null=True)),
                ('home', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('picture', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('user_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('phone_type_id', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
